# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opmsk < Formula
  desc "Mask 1Password CLI password using ANSI color."
  homepage "https://github.com/winebarrel/opmsk"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.4.1/opmsk_0.4.1_darwin_arm64.tar.gz"
      sha256 "54eaf8c597e8a8cc951c83894ea24119c194258bbe536419fdde1277860e84fa"

      def install
        bin.install 'opmsk'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.4.1/opmsk_0.4.1_darwin_amd64.tar.gz"
      sha256 "9da28f39915881eef8798fe341e528474eeda16b4e85d38119dd553aa03aa8fb"

      def install
        bin.install 'opmsk'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.4.1/opmsk_0.4.1_linux_arm64.tar.gz"
      sha256 "2f66481b15acb328dcc545367e976e38b12466b2c28fd3daef092d331ac1fd98"

      def install
        bin.install 'opmsk'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.4.1/opmsk_0.4.1_linux_amd64.tar.gz"
      sha256 "cf2f85352f725ac0896d6c0c28730ebf94c322647583a1ea1cc99fb8bc96dcfc"

      def install
        bin.install 'opmsk'
      end
    end
  end
end
