# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opmsk < Formula
  desc "Mask 1Password CLI password using ANSI color."
  homepage "https://github.com/winebarrel/opmsk"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.1/opmsk_0.3.1_darwin_amd64.tar.gz"
      sha256 "f1bfdb400c1fb9dad4913c64d66ebd81f15208b8ac02b30f547d25cc7eceef8a"

      def install
        bin.install 'opmsk'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.1/opmsk_0.3.1_darwin_arm64.tar.gz"
      sha256 "4e9388994c4893549af698eb1ccab260bedb263ed889a3c73b0b618a285d1726"

      def install
        bin.install 'opmsk'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.1/opmsk_0.3.1_linux_amd64.tar.gz"
      sha256 "e712c945408921fb01eeb04cc7de90d954cc40dea7a1476067c199f66928b276"

      def install
        bin.install 'opmsk'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.1/opmsk_0.3.1_linux_arm64.tar.gz"
      sha256 "3cfcc2f0736e0f8f29e238bc41389d41f44511c276ae5749ac63cfad7247bb9a"

      def install
        bin.install 'opmsk'
      end
    end
  end
end
