# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opmsk < Formula
  desc "Mask 1Password CLI password using ANSI color."
  homepage "https://github.com/winebarrel/opmsk"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.2/opmsk_0.3.2_darwin_arm64.tar.gz"
      sha256 "fd28aa814408eae91c31bb528adceb7b7ac10fe55a95c737cda24d0fb56f598d"

      def install
        bin.install 'opmsk'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.2/opmsk_0.3.2_darwin_amd64.tar.gz"
      sha256 "e3777e2e5e854cdbe24e4c266ca11d8fbe8141117ae7ef2f3b8b684b3a018dd1"

      def install
        bin.install 'opmsk'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.2/opmsk_0.3.2_linux_arm64.tar.gz"
      sha256 "51fc077f0e6470620b96936bee3530c7ed2a49e83e0066be62decf3821501ed6"

      def install
        bin.install 'opmsk'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/opmsk/releases/download/v0.3.2/opmsk_0.3.2_linux_amd64.tar.gz"
      sha256 "4b5978a42549bd17c74b208bccf17fbf80ab76bdcd0cac1c69319b3b598cc397"

      def install
        bin.install 'opmsk'
      end
    end
  end
end
